### ISSUE TITLE
unreachable code on windows

### ISSUE THREAD

**Issue by nobledemon** [imakris/glatter#3]
I get this in hundreds of lines:
`error C2220: the following warning is treated as an error
glatter_GL_e2s_def.h(92) : warning C4702: unreachable code`

However the program seems to work if I ignore that warning.
Excellent library otherwise, great work.

**Comment by imakris** [comment]
ok let me have a look...
which compiler are you using? do you get this with the wlxgears test too?

i am glad you like the library, thanks :)

**Comment by imakris** [comment]
I disabled the warning (it was a harmless W4 warning)
